version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: ionipay-postgres
    environment:
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - db_name
      - db_pass
    
  backend-app:
    build: .
    container_name: ionipay-spring-boot
    ports:
      - "8080:8080"
    depends_on: 
      - postgres-db

volumes:
  postgres_data:

secrets:
  db_pass:
    file: ./db_password.txt 
  db_name:
    file: ./db_name.txt